import pg from 'pg';

const { Pool } = pg;

let pool;

export function getDb() {
  if (!pool) {
    if (!process.env.DATABASE_URL) {
      throw new Error('DATABASE_URL is required for PostgreSQL persistence.');
    }

    pool = new Pool({
      connectionString: process.env.DATABASE_URL,
      ssl: process.env.DATABASE_SSL === 'false' ? false : { rejectUnauthorized: false }
    });
  }

  return pool;
}

export async function initDatabase() {
  const db = getDb();
  await db.query(`
    CREATE TABLE IF NOT EXISTS users (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS schedule_uploads (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      original_name TEXT NOT NULL,
      stored_name TEXT NOT NULL,
      file_data BYTEA,
      worksheet_name TEXT NOT NULL,
      header_row_index INTEGER NOT NULL,
      column_mapping_json TEXT NOT NULL,
      session_mapping_json TEXT NOT NULL,
      row_count INTEGER NOT NULL DEFAULT 0,
      active INTEGER NOT NULL DEFAULT 1,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS schedule_rows (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      upload_id INTEGER NOT NULL REFERENCES schedule_uploads(id) ON DELETE CASCADE,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      source_row_number INTEGER NOT NULL,
      school_faculty TEXT,
      class_code TEXT,
      course_code TEXT,
      course_name TEXT,
      notes TEXT,
      course_group TEXT,
      exam_period TEXT,
      week TEXT,
      day_of_week TEXT,
      exam_date_raw TEXT,
      exam_session TEXT,
      student_count TEXT,
      exam_room TEXT,
      exam_room_code TEXT,
      exam_time TEXT,
      exam_datetime TEXT,
      parse_warnings_json TEXT NOT NULL DEFAULT '[]',
      raw_json TEXT NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE IF NOT EXISTS selected_exams (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
      schedule_row_id INTEGER NOT NULL UNIQUE REFERENCES schedule_rows(id) ON DELETE CASCADE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
    );

    CREATE INDEX IF NOT EXISTS idx_schedule_rows_lookup
      ON schedule_rows(course_code, course_name);
    CREATE INDEX IF NOT EXISTS idx_schedule_rows_datetime
      ON schedule_rows(exam_datetime);
    CREATE INDEX IF NOT EXISTS idx_schedule_uploads_user_active
      ON schedule_uploads(user_id, active);
    CREATE INDEX IF NOT EXISTS idx_schedule_rows_user_lookup
      ON schedule_rows(user_id, course_code, course_name);
    CREATE INDEX IF NOT EXISTS idx_selected_exams_user
      ON selected_exams(user_id);
  `);
}

export async function withTransaction(callback) {
  const client = await getDb().connect();
  try {
    await client.query('BEGIN');
    const result = await callback(client);
    await client.query('COMMIT');
    return result;
  } catch (error) {
    await client.query('ROLLBACK');
    throw error;
  } finally {
    client.release();
  }
}
